name: Run Tests
on: push
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: node --version
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test
      - run: echo "🍏 This job's status is ${{ job.status }}."
