name: Tests
on: push
jobs:
  Setup-Repo-And-Run-Linter:
    name: Setup-Repo-And-Run-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
  Run-Tests:
    name: Run-Tests
    needs: Setup-Repo-And-Run-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: npm run test
